file_format: "1"
id: prototype
name: prototype/Sweep
type: shield
url: https://github.com/davidphilipbarr/Sweep
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - prototype_left
  - prototype_right
